trigger:
  branches:
    include:
      - feature/*
  paths:
    include:
      - src/shippingservice/**

pr: none

jobs:
- template: ../../pipelines/feature-ci-template.yaml
  parameters:
    serviceName: shippingservice
