apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice-deployment
  labels:
    app: cartservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: vg1988acr.azurecr.io/vajramgmicroservicesdemo:21
          ports:
            - containerPort: 7070
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "150m"
