apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  selector:
    app: cartservice
  ports:  
  - protocol: TCP 
    port: 7070 
    targetPort: 7070
  type: ClusterIP


