apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice-deployment
  labels:
    app: adservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: vg1988acr.azurecr.io/vajramgmicroservicesdemo:21
          ports:
            - containerPort: 9555
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
