trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/currencyservice/**

stages:
  - stage: build
    displayName: Build
    variables:
      - group: common-shared
    jobs:
      - template: ../../pipelines/build-template.yaml
        parameters:
          serviceName: currencyservice
  - stage: deploydev
    displayName: Deploy-DEV
    dependsOn: build
    variables:
      - group: common-dev
      - group: common-shared
    jobs:
      - template: ../../pipelines/deploy-template.yaml
        parameters:
          serviceName: currencyservice
          environmentName: DEV
  - stage: deployqa
    displayName: Deploy-QA
    dependsOn: deploy-dev
    variables:
      - group: common-qa
      - group: common-shared
    jobs:
      - template: ../../pipelines/deploy-template.yaml
        parameters:
          serviceName: currencyservice
          environmentName: QA
  - stage: deployprod
    displayName: Deploy-PROD
    dependsOn: deploy-qa
    variables:
      - group: common-prod
    jobs:
      - template: ../../pipelines/deploy-template.yaml
        parameters:
          serviceName: currencyservice
          environmentName: PROD
