trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/currencyservice/**

variables:
  - group: common-qa
stages:
  - stage: build
    displayName: Build
    jobs:
      - template: ../../pipelines/build-template.yaml
        parameters:
          serviceName: currencyservice
          acr: $(acr)
  - stage: deploy
    displayName: Deploy
    jobs:
      - template: ../../pipelines/deploy-template.yaml
        parameters:
          serviceName: currencyservice
          acr: $(acr)
          environmentName: QA
