trigger:
  branches:
    include:
      - develop
      - main
      - release/*
  paths:
    include:
      - src/currencyservice/**

pr:
  branches:
    include:
      - develop
  paths:
    include:
      - src/currencyservice/**

stages:
  # ==================================================
  # BUILD
  # ==================================================

  - stage: build
    displayName: Build

    variables:
      - group: common-shared

    jobs:
      - template: ../../pipelines/build-template.yaml
        parameters:
          serviceName: currencyservice

  # ==================================================
  # DEV
  # ==================================================

  - stage: deploydev
    displayName: Deploy-DEV

    dependsOn:
      - build

    condition: |
      and(
        succeeded(),
        eq(variables['Build.SourceBranch'], 'refs/heads/develop')
      )

    variables:
      - group: common-dev
      - group: common-shared

    jobs:
      - template: ../../pipelines/deploy-template.yaml
        parameters:
          serviceName: currencyservice
          environmentName: DEV

  # ==================================================
  # QA
  # ==================================================

  - stage: deployqa
    displayName: Deploy-QA

    dependsOn:
      - build

    condition: |
      and(
        succeeded(),
        startsWith(
          variables['Build.SourceBranch'],
          'refs/heads/release/'
        )
      )

    variables:
      - group: common-qa
      - group: common-shared

    jobs:
      - template: ../../pipelines/deploy-template.yaml
        parameters:
          serviceName: currencyservice
          environmentName: QA

  # ==================================================
  # PROD
  # ==================================================

  - stage: deployprod
    displayName: Deploy-PROD

    dependsOn:
      - build

    condition: |
      and(
        succeeded(),
        eq(variables['Build.SourceBranch'], 'refs/heads/main')
      )

    variables:
      - group: common-prod
      - group: common-shared

    jobs:
      - template: ../../pipelines/deploy-template.yaml
        parameters:
          serviceName: currencyservice
          environmentName: PROD
