trigger: none

pr:
  branches:
    include:
      - develop
      - release/*
      - main

  paths:
    include:
      - src/cartservice/**

jobs:
- template: ../../pipelines/feature-ci-template.yaml
  parameters:
    serviceName: cartservice
