trigger:
  branches:
    include:
      - feature/*
  paths:
    include:
      - src/cartservice/**

pr: none

jobs:
- template: ../../pipelines/feature-ci-template.yaml
  parameters:
    serviceName: cartservice