apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice-deployment
  labels:
    app: checkout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout
        image: vg1988acr.azurecr.io/checkoutservice:70
        ports:
        - containerPort: 5050
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: shipping
          value: "shippingservice:50051"