apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  labels:
    app: checkout
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: checkout
  ports:
    - port: 5050
      targetPort: 5050
      
    