parameters:
    - name: serviceName
      type: string

    - name: acr
      type: string
      
jobs:
    - job: build
      pool:
        vmImage: 'ubuntu-latest'
      displayName: Build
      steps:
       - task: AzureCLI@3
         inputs:
           connectionType: 'azureRM'
           azureSubscription: 'az-resource'
           scriptType: 'bash'
           scriptLocation: 'inlineScript'
           inlineScript: |
            az acr login --name ${{ parameters.acr }}

            pwd
            ls -ltr
            docker build \
            -t ${{ parameters.acr }}.azurecr.io/${{ parameters.serviceName }}:$(Build.BuildId) \
            .src/${{ parameters.serviceName }}
            docker push \
            ${{ parameters.acr }}.azurecr.io/${{ parameters.serviceName }}:$(Build.BuildId)