parameters:
    - name: servicename
      type: string

      variables:
        acr: vg1988myacr.azurecr.io
      
jobs:
    - job: build
      displayName: Build
      steps:
       - task: AzureCLI@3
         inputs:
           connectionType: 'azureRM'
           azureSubscription: 'az-resource'
           scriptType: 'bash'
           scriptLocation: 'inlineScript'
           inlineScript: |
           az acr login --name vg1988myacr 

            docker build \

            -t ${{ variables.acr }}/${{ parameters.serviceName }}:$(Build.BuildId) \

            ./src/${{ parameters.serviceName }}

            docker push \
            ${{ variables.acr }}/${{ parameters.serviceName }}:$(Build.BuildId)
