parameters:
    - name: serviceName
      type: string
      
jobs:
    - job: build
      pool:
        vmImage: 'ubuntu-latest'
      displayName: Build
      variables:
      - group: common-shared
      steps:
       - task: AzureCLI@3
         inputs:
           connectionType: 'azureRM'
           azureSubscription: 'az-resource'
           scriptType: 'bash'
           scriptLocation: 'inlineScript'
           inlineScript: |
            az acr login --name $(acr)

            pwd
            ls -ltr
            docker build \
            -t $(acr).azurecr.io/${{ parameters.serviceName }}:$(Build.BuildId) \
            src/${{ parameters.serviceName }}
            docker push \
            $(acr).azurecr.io/${{ parameters.serviceName }}:$(Build.BuildId)