parameters:
    - name: serviceName
      type: string
    - name: environmentName
      type: string
jobs:
- deployment: deploy
  displayName: 'Deploy to AKS'
  environment: ${{parameters.environmentName}}
  variables:
  - group: common-shared
  - group: common-dev
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
       runOnce:
        deploy:
         steps:
         - checkout: self 
         - script: |
            echo "Current directory:"
            pwd
            echo "Repository structure:"
            ls -R
           displayName: "Debug Repository"

         - task: kubernetes@1
           inputs:
             connectionType: 'Azure Resource Manager'
             azureSubscriptionEndpoint: 'az-resource'
             azureResourceGroup: $(azureResourceGroup)
             kubernetesCluster: $(kubernetesCluster)
             command: 'login'
         - script: |
             kubectl create namespace $(namespace) --dry-run=client -o yaml | kubectl apply -f -
           displayName: Create Namespace
         - task: KubernetesManifest@1
           inputs:
            action: 'deploy'
            connectionType: 'Azure Resource Manager'
            azureSubscriptionConnection: 'az-resource'
            azureResourceGroup: $(azureResourceGroup)
            kubernetesCluster: $(kubernetesCluster)
            namespace: $(namespace)
            manifests: |
             src/${{ parameters.serviceName }}/manifests/deployment.yaml
             src/${{ parameters.serviceName }}/manifests/service.yaml 
            containers: |
             $(acr).azurecr.io/${{ parameters.serviceName }}:$(Build.BuildId)