parameters:
    - name: serviceName
      type: string
    - name: acr
      type: string
    - name: environmentName
      type: string
jobs:
- deployment: deploy
  displayName: 'Deploy to AKS'
  environment: ${{parameters.environmentName}}
  pool:
    vm-image: 'ubuntu-latest'
  strategy:
       runOnce:
        deploy:
         steps:
         - task: KubernetesManifest@1
           inputs:
            action: 'deploy'
            connectionType: 'azureResourceManager'
            azureSubscriptionConnection: 'az-resource'
            azureResourceGroup: 'aks-rg'
            kubernetesCluster: 'my-aks1988'
            namespace: $(namespace)
            manifests: |
            src/${{ parameters.serviceName }}/manifests/deployment.yaml
            src/${{ parameters.serviceName }}/manifests/service.yaml 
            containers: |
            ${{ parameters.acr }}.azurecr.io/${{ parameters.serviceName }}:$(Build.BuildId)