parameters:
    - name: servicename
      type: string

  variables:
    acr: vg1988myacr.azurecr.io
jobs:
    - job: build
      displayName: Build
      steps:
       - task: KubernetesManifest@1
         inputs:
           action: 'deploy'
           connectionType: 'azureResourceManager'
           azureSubscriptionConnection: 'az-resource'
           azureResourceGroup: 'aks-rg'
           kubernetesCluster: 'my-aks1988'
           namespace: 'default'
           manifests: |
           src/${{ parameters.servicename }}/manifests/deployment.yaml 
           src/${{ parameters.servicename }}/manifests/service.yaml 
           containers: 
             ${{ variables.acr }}/${{ parameters.serviceName }}:$(Build.BuildId)
