trigger:
  branches:
    include:
      - src/checkoutservice/**
variables:
  acr: vg1988acr
stages:
  - stage: build
    displayName: Build
    jobs:
      - template: ../../pipelines/build-template.yaml
        parameters:
          serviceName: checkoutservice
          acr: $(acr)
  - stage: deploy
    displayName: Deploy
    jobs:
      - template: ../../pipelines/deploy-template.yaml
        parameters:
          serviceName: checkoutservice
          acr: $(acr)
