trigger:
  branches:
    include:
      - main # or develop, feature/*

  paths:
    include:
      - src/adservice/**

variables:
  acr: "acrvg1988"
stages:
  - stage: build
    displayName: Build
    jobs:
      - template: ../../pipelines/build-template.yaml
        parameters:
          serviceName: adservice
          acr: $(acr)
  - stage: deploy
    displayName: Deploy
    jobs:
      - template: ../../pipelines/deploy-template.yaml
        parameters:
          serviceName: adservice
          environmentName: DEV
