trigger:
  branches:
    include:
      - src/adservice/**

variables:
  acr: "acrvg1988"
stages:
  - stage: build
    displayName: Build
    jobs:
      - template: ../../pipelines/build-template.yaml
        parameters:
          serviceName: adservice
          acr: acrvg1988
  - stage: deploy
    displayName: Deploy
    jobs:
      - template: ../../pipelines/deploy-template.yaml
        parameters:
          serviceName: adservice
          acr: acrvg1988
