#Build Platform
ARG BUILDPLATFORM=linux/amd64
#Build Stage
FROM --platform=$BUILDPLATFORM eclipse-temurin:24.0.2_12-jdk-noble@sha256:dacac8e9a0df0d2bd24e702b4431132875c249930b70555ebd7ca285b5bee684 AS builder
#Working Directory
WORKDIR /app
#test build docker
COPY gradlew build.gradle ./
COPY gradle ./gradle
RUN chmod +x gradlew
RUN ./gradlew downloadRepos  
COPY . .
RUN chmod +x gradlew
RUN ./gradlew installDist
#Run Stage testing and packing of this app
FROM eclipse-temurin:25.0.2_10-jre-alpine@sha256:5fcc27581b238efbfda93da3a103f59e0b5691fe522a7ac03fe8057b0819c888
WORKDIR /app
COPY --from=builder /app .
EXPOSE 9555
#this is entrypoint for the adservice testing dockerfile
ENTRYPOINT ["/app/build/install/hipstershop/bin/AdService"]